version: '3.1'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/.pgdata/gpx-dashboard:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=gpx-db
